services:
  - type: web
    name: n8n
    env: node
    runtime: node
    nodeVersion: 20.11.1
    buildCommand: |
      curl -fsSL https://fnm.vercel.app/install | bash && 
      export PATH="/root/.local/share/fnm:$PATH" && 
      eval "`fnm env`" && 
      fnm install 20.11.1 && 
      fnm use 20.11.1 && 
      NODE_ENV=production pnpm install --frozen-lockfile && 
      pnpm build
    startCommand: |
      curl -fsSL https://fnm.vercel.app/install | bash && 
      export PATH="/root/.local/share/fnm:$PATH" && 
      eval "`fnm env`" && 
      fnm install 20.11.1 && 
      fnm use 20.11.1 && 
      pnpm start
    # Health check configuration
    healthCheckPath: /healthz
    # Auto-deploy settings
    autoDeploy: true
    # Resource allocation
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_URL}
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: "3000"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      # Database configuration
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Additional recommended configurations
      - key: N8N_EDITOR_BASE_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: N8N_METRICS
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "true"
      - key: N8N_HIRING_BANNER_ENABLED
        value: "false"
      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: "true"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n
    plan: free
    ipAllowList: [] 