services:
  - type: web
    name: n8n
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    # Health check configuration
    healthCheckPath: /healthz
    # Auto-deploy settings
    autoDeploy: true
    # Resource allocation
    plan: starter # You can upgrade to 'standard' or 'pro' based on your needs
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_URL}
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: "3000"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      # Database configuration
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      # Additional recommended configurations
      - key: N8N_EDITOR_BASE_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: N8N_METRICS
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "true"
      - key: N8N_HIRING_BANNER_ENABLED
        value: "false"
      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: "true"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false # You'll need to set this manually in Render dashboard
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false # You'll need to set this manually in Render dashboard

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n
    plan: free # Using the free tier for development
    # Database configuration
    ipAllowList: [] # Empty means only internal access 